// <auto-generated />
using System;
using Kolos2APBD.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolos2APBD.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250613110544_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtworkExhibitionArtwork", b =>
                {
                    b.Property<int>("ArtworksArtworkId")
                        .HasColumnType("int");

                    b.Property<int>("ExhibitionArtworksExhibitionId")
                        .HasColumnType("int");

                    b.Property<int>("ExhibitionArtworksArtworkId")
                        .HasColumnType("int");

                    b.HasKey("ArtworksArtworkId", "ExhibitionArtworksExhibitionId", "ExhibitionArtworksArtworkId");

                    b.HasIndex("ExhibitionArtworksExhibitionId", "ExhibitionArtworksArtworkId");

                    b.ToTable("ArtworkExhibitionArtwork");
                });

            modelBuilder.Entity("Kolos2APBD.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artist");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            BirthDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Doe"
                        },
                        new
                        {
                            ArtistId = 2,
                            BirthDate = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marek",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            ArtistId = 3,
                            BirthDate = new DateTime(2025, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mirosław",
                            LastName = "Krupiewnicki"
                        });
                });

            modelBuilder.Entity("Kolos2APBD.Models.Artwork", b =>
                {
                    b.Property<int>("ArtworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtworkId"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YearCreated")
                        .HasColumnType("int");

                    b.HasKey("ArtworkId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Artwork");

                    b.HasData(
                        new
                        {
                            ArtworkId = 1,
                            ArtistId = 1,
                            Title = "KolosNamalowany",
                            YearCreated = 2004
                        },
                        new
                        {
                            ArtworkId = 2,
                            ArtistId = 2,
                            Title = "Oobrotachsferniebieskich",
                            YearCreated = 2005
                        },
                        new
                        {
                            ArtworkId = 3,
                            ArtistId = 3,
                            Title = "Obrazobrazowy",
                            YearCreated = 2006
                        });
                });

            modelBuilder.Entity("Kolos2APBD.Models.Exhibition", b =>
                {
                    b.Property<int>("ExhibitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExhibitionId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExhibitionArtworkArtworkId")
                        .HasColumnType("int");

                    b.Property<int?>("ExhibitionArtworkExhibitionId")
                        .HasColumnType("int");

                    b.Property<int>("GalleryId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfArtworks")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ExhibitionId");

                    b.HasIndex("GalleryId");

                    b.HasIndex("ExhibitionArtworkExhibitionId", "ExhibitionArtworkArtworkId");

                    b.ToTable("Exhibition");

                    b.HasData(
                        new
                        {
                            ExhibitionId = 1,
                            EndDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 1,
                            NumberOfArtworks = 5,
                            StartDate = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wystawa1"
                        },
                        new
                        {
                            ExhibitionId = 2,
                            EndDate = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 1,
                            NumberOfArtworks = 6,
                            StartDate = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wystawa2"
                        },
                        new
                        {
                            ExhibitionId = 3,
                            EndDate = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 1,
                            NumberOfArtworks = 7,
                            StartDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wystawa3"
                        });
                });

            modelBuilder.Entity("Kolos2APBD.Models.ExhibitionArtwork", b =>
                {
                    b.Property<int>("ExhibitionId")
                        .HasColumnType("int");

                    b.Property<int>("ArtworkId")
                        .HasColumnType("int");

                    b.Property<decimal>("InsuranceValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric");

                    b.HasKey("ExhibitionId", "ArtworkId");

                    b.ToTable("Exhibition_Artwork");

                    b.HasData(
                        new
                        {
                            ExhibitionId = 1,
                            ArtworkId = 1,
                            InsuranceValue = 1000m
                        },
                        new
                        {
                            ExhibitionId = 1,
                            ArtworkId = 3,
                            InsuranceValue = 2000m
                        },
                        new
                        {
                            ExhibitionId = 2,
                            ArtworkId = 2,
                            InsuranceValue = 3000m
                        });
                });

            modelBuilder.Entity("Kolos2APBD.Models.Gallery", b =>
                {
                    b.Property<int>("GalleryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GalleryId"));

                    b.Property<DateTime>("EstablishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GalleryId");

                    b.ToTable("Gallery");

                    b.HasData(
                        new
                        {
                            GalleryId = 1,
                            EstablishedDate = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wystawa1"
                        });
                });

            modelBuilder.Entity("ArtworkExhibitionArtwork", b =>
                {
                    b.HasOne("Kolos2APBD.Models.Artwork", null)
                        .WithMany()
                        .HasForeignKey("ArtworksArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolos2APBD.Models.ExhibitionArtwork", null)
                        .WithMany()
                        .HasForeignKey("ExhibitionArtworksExhibitionId", "ExhibitionArtworksArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kolos2APBD.Models.Artwork", b =>
                {
                    b.HasOne("Kolos2APBD.Models.Artist", "Artist")
                        .WithMany("Artworks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Kolos2APBD.Models.Exhibition", b =>
                {
                    b.HasOne("Kolos2APBD.Models.Gallery", "Gallery")
                        .WithMany("Exhibitions")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolos2APBD.Models.ExhibitionArtwork", null)
                        .WithMany("Exhibitions")
                        .HasForeignKey("ExhibitionArtworkExhibitionId", "ExhibitionArtworkArtworkId");

                    b.Navigation("Gallery");
                });

            modelBuilder.Entity("Kolos2APBD.Models.Artist", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("Kolos2APBD.Models.ExhibitionArtwork", b =>
                {
                    b.Navigation("Exhibitions");
                });

            modelBuilder.Entity("Kolos2APBD.Models.Gallery", b =>
                {
                    b.Navigation("Exhibitions");
                });
#pragma warning restore 612, 618
        }
    }
}
